fix: more documentation and adjusting session settings

diff --git a/helm/applications/canfar/skaha/templates/configmap.yaml b/helm/applications/canfar/skaha/templates/configmap.yaml
--- a/helm/applications/canfar/skaha/templates/configmap.yaml
+++ b/helm/applications/canfar/skaha/templates/configmap.yaml
@@ -37,3 +37,50 @@ data:
         {{- if .Values.applicationName }}
         mv skaha.war {{ .Values.applicationName }}.war
         {{- end }}
+
+---
+# ConfigMap for the scripts to write out the /etc/passwd and /etc/group files with the
+# CADC users and groups from Redis.
+# This ConfigMap is mounted into the User Session Pods.
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: {{ .Release.Name }}-init-users-groups-config
+  namespace: {{ .Release.Namespace }}
+data:
+  init-users-groups.sh: |
+    #!/bin/sh
+
+    # It is expected that /etc-passwd and /etc-group exist and contain the original passwd files
+    # named passwd-orig and group-orig respectively.
+
+    # REDIS_URL expected to be in the environment.
+    # env:
+    #   - name: REDIS_URL
+    #     value: http://example.org:6359
+    #
+
+    SAVEIFS=$IFS
+    IFS='\n'
+
+    if [[ -z "${REDIS_URL}" ]]; then
+        echo "Required argument REDIS_URL is missing."
+        exit 1
+    else
+        echo "Using REDIS_URL: ${REDIS_URL}"
+    fi  
+
+    TARGET_PASSWD_FILE="/etc-passwd/passwd"
+    TARGET_GROUP_FILE="/etc-group/group"
+
+    # Create (or overwrite) the files
+    cat /etc-passwd/passwd-orig > "${TARGET_PASSWD_FILE}"
+    cat /etc-group/group-orig > "${TARGET_GROUP_FILE}"
+
+    # Append Science Platform users
+    redis-cli -u "${REDIS_URL}" --raw smembers "users:posix" >> "${TARGET_PASSWD_FILE}"
+    redis-cli -u "${REDIS_URL}" --raw smembers "groups:posix" >> "${TARGET_GROUP_FILE}"
+
+    # restore $IFS
+    IFS=$SAVEIFS
+
